name: Build
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DH_USERNAME}}
          password: ${{secrets.DH_PASSWORD}}

      - name: 'Install Yarn'
        run: 'npm i -g yarn'

      - name: 'Install Dependencies'
        run: yarn

      - name: 'nx build'
        run: npx nx affected --target=docker
